/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimeTrackingIndexRouteImport } from './routes/time-tracking/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as RolesIndexRouteImport } from './routes/roles/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ManagementIndexRouteImport } from './routes/management/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as CallbackIndexRouteImport } from './routes/callback/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as TimeTrackingTimesheetIndexRouteImport } from './routes/time-tracking/timesheet/index'
import { Route as TimeTrackingRequestsIndexRouteImport } from './routes/time-tracking/requests/index'
import { Route as TimeTrackingPendingReviewIndexRouteImport } from './routes/time-tracking/pending-review/index'
import { Route as TimeTrackingManageRequestsIndexRouteImport } from './routes/time-tracking/manage-requests/index'
import { Route as TasksWeeklyIndexRouteImport } from './routes/tasks/weekly/index'
import { Route as TasksTagsIndexRouteImport } from './routes/tasks/tags/index'
import { Route as TasksSprintsIndexRouteImport } from './routes/tasks/sprints/index'
import { Route as TasksPerformanceIndexRouteImport } from './routes/tasks/performance/index'
import { Route as ManagementUsersIndexRouteImport } from './routes/management/users/index'
import { Route as ManagementUserManagementIndexRouteImport } from './routes/management/user-management/index'
import { Route as CalendarMeetingsIndexRouteImport } from './routes/calendar/meetings/index'
import { Route as ManagementUsersUserIdRouteImport } from './routes/management/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackingIndexRoute = TimeTrackingIndexRouteImport.update({
  id: '/time-tracking/',
  path: '/time-tracking/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesIndexRoute = RolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementIndexRoute = ManagementIndexRouteImport.update({
  id: '/management/',
  path: '/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackIndexRoute = CallbackIndexRouteImport.update({
  id: '/callback/',
  path: '/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackingTimesheetIndexRoute =
  TimeTrackingTimesheetIndexRouteImport.update({
    id: '/time-tracking/timesheet/',
    path: '/time-tracking/timesheet/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TimeTrackingRequestsIndexRoute =
  TimeTrackingRequestsIndexRouteImport.update({
    id: '/time-tracking/requests/',
    path: '/time-tracking/requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TimeTrackingPendingReviewIndexRoute =
  TimeTrackingPendingReviewIndexRouteImport.update({
    id: '/time-tracking/pending-review/',
    path: '/time-tracking/pending-review/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TimeTrackingManageRequestsIndexRoute =
  TimeTrackingManageRequestsIndexRouteImport.update({
    id: '/time-tracking/manage-requests/',
    path: '/time-tracking/manage-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TasksWeeklyIndexRoute = TasksWeeklyIndexRouteImport.update({
  id: '/tasks/weekly/',
  path: '/tasks/weekly/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTagsIndexRoute = TasksTagsIndexRouteImport.update({
  id: '/tasks/tags/',
  path: '/tasks/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksSprintsIndexRoute = TasksSprintsIndexRouteImport.update({
  id: '/tasks/sprints/',
  path: '/tasks/sprints/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksPerformanceIndexRoute = TasksPerformanceIndexRouteImport.update({
  id: '/tasks/performance/',
  path: '/tasks/performance/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementUsersIndexRoute = ManagementUsersIndexRouteImport.update({
  id: '/management/users/',
  path: '/management/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementUserManagementIndexRoute =
  ManagementUserManagementIndexRouteImport.update({
    id: '/management/user-management/',
    path: '/management/user-management/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CalendarMeetingsIndexRoute = CalendarMeetingsIndexRouteImport.update({
  id: '/calendar/meetings/',
  path: '/calendar/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementUsersUserIdRoute = ManagementUsersUserIdRouteImport.update({
  id: '/management/users/$userId',
  path: '/management/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/account': typeof AccountIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/callback': typeof CallbackIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/home': typeof HomeIndexRoute
  '/legal': typeof LegalIndexRoute
  '/management': typeof ManagementIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/roles': typeof RolesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/time-tracking': typeof TimeTrackingIndexRoute
  '/management/users/$userId': typeof ManagementUsersUserIdRoute
  '/calendar/meetings': typeof CalendarMeetingsIndexRoute
  '/management/user-management': typeof ManagementUserManagementIndexRoute
  '/management/users': typeof ManagementUsersIndexRoute
  '/tasks/performance': typeof TasksPerformanceIndexRoute
  '/tasks/sprints': typeof TasksSprintsIndexRoute
  '/tasks/tags': typeof TasksTagsIndexRoute
  '/tasks/weekly': typeof TasksWeeklyIndexRoute
  '/time-tracking/manage-requests': typeof TimeTrackingManageRequestsIndexRoute
  '/time-tracking/pending-review': typeof TimeTrackingPendingReviewIndexRoute
  '/time-tracking/requests': typeof TimeTrackingRequestsIndexRoute
  '/time-tracking/timesheet': typeof TimeTrackingTimesheetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/account': typeof AccountIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/callback': typeof CallbackIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/home': typeof HomeIndexRoute
  '/legal': typeof LegalIndexRoute
  '/management': typeof ManagementIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/roles': typeof RolesIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/time-tracking': typeof TimeTrackingIndexRoute
  '/management/users/$userId': typeof ManagementUsersUserIdRoute
  '/calendar/meetings': typeof CalendarMeetingsIndexRoute
  '/management/user-management': typeof ManagementUserManagementIndexRoute
  '/management/users': typeof ManagementUsersIndexRoute
  '/tasks/performance': typeof TasksPerformanceIndexRoute
  '/tasks/sprints': typeof TasksSprintsIndexRoute
  '/tasks/tags': typeof TasksTagsIndexRoute
  '/tasks/weekly': typeof TasksWeeklyIndexRoute
  '/time-tracking/manage-requests': typeof TimeTrackingManageRequestsIndexRoute
  '/time-tracking/pending-review': typeof TimeTrackingPendingReviewIndexRoute
  '/time-tracking/requests': typeof TimeTrackingRequestsIndexRoute
  '/time-tracking/timesheet': typeof TimeTrackingTimesheetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/account/': typeof AccountIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/callback/': typeof CallbackIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/home/': typeof HomeIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/management/': typeof ManagementIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/roles/': typeof RolesIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/time-tracking/': typeof TimeTrackingIndexRoute
  '/management/users/$userId': typeof ManagementUsersUserIdRoute
  '/calendar/meetings/': typeof CalendarMeetingsIndexRoute
  '/management/user-management/': typeof ManagementUserManagementIndexRoute
  '/management/users/': typeof ManagementUsersIndexRoute
  '/tasks/performance/': typeof TasksPerformanceIndexRoute
  '/tasks/sprints/': typeof TasksSprintsIndexRoute
  '/tasks/tags/': typeof TasksTagsIndexRoute
  '/tasks/weekly/': typeof TasksWeeklyIndexRoute
  '/time-tracking/manage-requests/': typeof TimeTrackingManageRequestsIndexRoute
  '/time-tracking/pending-review/': typeof TimeTrackingPendingReviewIndexRoute
  '/time-tracking/requests/': typeof TimeTrackingRequestsIndexRoute
  '/time-tracking/timesheet/': typeof TimeTrackingTimesheetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks/$taskId'
    | '/account'
    | '/calendar'
    | '/callback'
    | '/forgot-password'
    | '/home'
    | '/legal'
    | '/management'
    | '/register'
    | '/reset-password'
    | '/roles'
    | '/tasks'
    | '/time-tracking'
    | '/management/users/$userId'
    | '/calendar/meetings'
    | '/management/user-management'
    | '/management/users'
    | '/tasks/performance'
    | '/tasks/sprints'
    | '/tasks/tags'
    | '/tasks/weekly'
    | '/time-tracking/manage-requests'
    | '/time-tracking/pending-review'
    | '/time-tracking/requests'
    | '/time-tracking/timesheet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks/$taskId'
    | '/account'
    | '/calendar'
    | '/callback'
    | '/forgot-password'
    | '/home'
    | '/legal'
    | '/management'
    | '/register'
    | '/reset-password'
    | '/roles'
    | '/tasks'
    | '/time-tracking'
    | '/management/users/$userId'
    | '/calendar/meetings'
    | '/management/user-management'
    | '/management/users'
    | '/tasks/performance'
    | '/tasks/sprints'
    | '/tasks/tags'
    | '/tasks/weekly'
    | '/time-tracking/manage-requests'
    | '/time-tracking/pending-review'
    | '/time-tracking/requests'
    | '/time-tracking/timesheet'
  id:
    | '__root__'
    | '/'
    | '/tasks/$taskId'
    | '/account/'
    | '/calendar/'
    | '/callback/'
    | '/forgot-password/'
    | '/home/'
    | '/legal/'
    | '/management/'
    | '/register/'
    | '/reset-password/'
    | '/roles/'
    | '/tasks/'
    | '/time-tracking/'
    | '/management/users/$userId'
    | '/calendar/meetings/'
    | '/management/user-management/'
    | '/management/users/'
    | '/tasks/performance/'
    | '/tasks/sprints/'
    | '/tasks/tags/'
    | '/tasks/weekly/'
    | '/time-tracking/manage-requests/'
    | '/time-tracking/pending-review/'
    | '/time-tracking/requests/'
    | '/time-tracking/timesheet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CallbackIndexRoute: typeof CallbackIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  ManagementIndexRoute: typeof ManagementIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  RolesIndexRoute: typeof RolesIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TimeTrackingIndexRoute: typeof TimeTrackingIndexRoute
  ManagementUsersUserIdRoute: typeof ManagementUsersUserIdRoute
  CalendarMeetingsIndexRoute: typeof CalendarMeetingsIndexRoute
  ManagementUserManagementIndexRoute: typeof ManagementUserManagementIndexRoute
  ManagementUsersIndexRoute: typeof ManagementUsersIndexRoute
  TasksPerformanceIndexRoute: typeof TasksPerformanceIndexRoute
  TasksSprintsIndexRoute: typeof TasksSprintsIndexRoute
  TasksTagsIndexRoute: typeof TasksTagsIndexRoute
  TasksWeeklyIndexRoute: typeof TasksWeeklyIndexRoute
  TimeTrackingManageRequestsIndexRoute: typeof TimeTrackingManageRequestsIndexRoute
  TimeTrackingPendingReviewIndexRoute: typeof TimeTrackingPendingReviewIndexRoute
  TimeTrackingRequestsIndexRoute: typeof TimeTrackingRequestsIndexRoute
  TimeTrackingTimesheetIndexRoute: typeof TimeTrackingTimesheetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking/': {
      id: '/time-tracking/'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles/': {
      id: '/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/': {
      id: '/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/': {
      id: '/callback/'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking/timesheet/': {
      id: '/time-tracking/timesheet/'
      path: '/time-tracking/timesheet'
      fullPath: '/time-tracking/timesheet'
      preLoaderRoute: typeof TimeTrackingTimesheetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking/requests/': {
      id: '/time-tracking/requests/'
      path: '/time-tracking/requests'
      fullPath: '/time-tracking/requests'
      preLoaderRoute: typeof TimeTrackingRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking/pending-review/': {
      id: '/time-tracking/pending-review/'
      path: '/time-tracking/pending-review'
      fullPath: '/time-tracking/pending-review'
      preLoaderRoute: typeof TimeTrackingPendingReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking/manage-requests/': {
      id: '/time-tracking/manage-requests/'
      path: '/time-tracking/manage-requests'
      fullPath: '/time-tracking/manage-requests'
      preLoaderRoute: typeof TimeTrackingManageRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/weekly/': {
      id: '/tasks/weekly/'
      path: '/tasks/weekly'
      fullPath: '/tasks/weekly'
      preLoaderRoute: typeof TasksWeeklyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/tags/': {
      id: '/tasks/tags/'
      path: '/tasks/tags'
      fullPath: '/tasks/tags'
      preLoaderRoute: typeof TasksTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/sprints/': {
      id: '/tasks/sprints/'
      path: '/tasks/sprints'
      fullPath: '/tasks/sprints'
      preLoaderRoute: typeof TasksSprintsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/performance/': {
      id: '/tasks/performance/'
      path: '/tasks/performance'
      fullPath: '/tasks/performance'
      preLoaderRoute: typeof TasksPerformanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/users/': {
      id: '/management/users/'
      path: '/management/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof ManagementUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/user-management/': {
      id: '/management/user-management/'
      path: '/management/user-management'
      fullPath: '/management/user-management'
      preLoaderRoute: typeof ManagementUserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/meetings/': {
      id: '/calendar/meetings/'
      path: '/calendar/meetings'
      fullPath: '/calendar/meetings'
      preLoaderRoute: typeof CalendarMeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/users/$userId': {
      id: '/management/users/$userId'
      path: '/management/users/$userId'
      fullPath: '/management/users/$userId'
      preLoaderRoute: typeof ManagementUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CallbackIndexRoute: CallbackIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  ManagementIndexRoute: ManagementIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TimeTrackingIndexRoute: TimeTrackingIndexRoute,
  ManagementUsersUserIdRoute: ManagementUsersUserIdRoute,
  CalendarMeetingsIndexRoute: CalendarMeetingsIndexRoute,
  ManagementUserManagementIndexRoute: ManagementUserManagementIndexRoute,
  ManagementUsersIndexRoute: ManagementUsersIndexRoute,
  TasksPerformanceIndexRoute: TasksPerformanceIndexRoute,
  TasksSprintsIndexRoute: TasksSprintsIndexRoute,
  TasksTagsIndexRoute: TasksTagsIndexRoute,
  TasksWeeklyIndexRoute: TasksWeeklyIndexRoute,
  TimeTrackingManageRequestsIndexRoute: TimeTrackingManageRequestsIndexRoute,
  TimeTrackingPendingReviewIndexRoute: TimeTrackingPendingReviewIndexRoute,
  TimeTrackingRequestsIndexRoute: TimeTrackingRequestsIndexRoute,
  TimeTrackingTimesheetIndexRoute: TimeTrackingTimesheetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
